name: meet_note_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com
# author: stesc <ste.schaller@gmx.de>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  uuid: ^2.0.1
  injector: ^1.0.8
  stateful_view_model:
    git:
      url: git://github.com/tikkrapp/stateful_view_model.git

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.0.0
