name: meet_note_web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: stesc <ste.schaller@gmx.de>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  injector: ^1.0.8
  meet_note_core:
    path: ../meet_note_core
  angular: ^5.2.0
  angular_components: ^0.11.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
